version: '3.3'
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: './.docker/Dockerfile'
    ports:
      - ${PORT:-53100}:${PORT:-53100}
    restart: always
    command: 'npm run serve:ssr'
